### PR TITLE
Feature/add proptype meta loader

### PR DESCRIPTION
**Pull request by Reasonable-Solutions**
@asbjornh

### CODE REVIEW

**Comment by asbjornh** [comment]
Actually, when I think about it, wouldn't it be better if this was a babel plugin instead of a webpack loader? That way we wouldn't have to do our own parsing and generating. We can just provide the two visitors, like [here](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#toc-plugin-options), and babel will do the rest.

The webpack plugin reads source files from disk anyway, so removing propTypesMeta from compiled files should cause no problems.

`.babelrc` could probably look something like this:

```
{
  "plugins": ["@creuna/prop-types-csharp-webpack-plugin/babel-plugin"]
}
```

**Comment by Reasonable-Solutions** [comment]
>  Actually, when I think about it, wouldn't it be better if this was a babel plugin instead of a webpack loader? That way we wouldn't have to do our own parsing and generating. We can just provide the two visitors, like here, and babel will do the rest.

Yes! This is exactly more correct!

**Comment by Reasonable-Solutions** [comment]
and, in retrospect, perhaps just calling remove after building the proptypesmeta object!

**Comment by asbjornh** [comment]
What? 🤔

**Comment by asbjornh** [comment]
I was bored so I made a babel plugin like I described in #9

**Comment by asbjornh** [comment]
#9 is merged. Closing this

**Pull request closed without merging**
